### ISSUE TITLE
Cannot get this to work 

### ISSUE THREAD

**Issue by Lucyhutch50** [marco110/LibPostalNet_1#1]
I am trying to explore this dot.net implementation of libpostal.
I had downloaded the original version and followed the instruction to build the windows dll, but then saw that this had links to recommended dll.

I have managed to build the .net under Visual Studio 2017 but if I try and run libpostalconsole I get

Loading LibPostal...

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libpostal': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at LibPostalNet.LibPostal.UnsafeNativeMethods.Setup()
   at LibPostalNet.LibPostal..ctor(String dataDir) in C:\LibPostalNet-master\LibPostalNet-master\LibPostalNet\LibPostal.cs:line 72
   at LibPostalNet.LibPostal.GetInstance(String dataDir) in C:\LibPostalNet-master\LibPostalNet-master\LibPostalNet\LibPostal.cs:line 12
   at LibPostalNet.LibPostal.GetInstance() in C:\LibPostalNet-master\LibPostalNet-master\LibPostalNet\LibPostal.cs:line 11
   at LibPostalConsole.Program.Main(String[] args) in C:\LibPostalNet-master\LibPostalNet-master\LibPostalConsole\Program.cs:line 13

My ultimate goal is to be able to build this, test and this and then use the .NET components in a Delphi program.

Anyone who can help please?
Thanks
Phil

**Comment by marco110** [comment]
I did testing for this library many months ago and I am failed too, I am sorry that I can't give you any help. Please refer to https://github.com/openvenues/libpostal to get more help.

Thanks,
Marco
